### ISSUE TITLE
Build an AppImage freeze from a working version

### ISSUE THREAD

**Issue by revast** [aalex/toonloop#21]
looks like development has stalled. which is sad.

but it is what it is, and as technology never stands still, it gets harder and harder to get at least SOMETHING running so that people can actually at least use the Software "As Is". 
Speaking of that, I would suggest to build an AppImage with one of the working versions, e.g 2.2.2-2-precise-ppa1 . 
So that involves setting up Ubuntu Precise in a VM, installing the AppImage tools and then generating the AppImage with toonloop. This AppImage then should normally run on every platform which is newer, preserving toonloop to get lost because of outdated dependencies (Gstreamer 0.10 for the most part). Then it would be a Matter of just updating the Homepage to point to the Appimge, and get rid of the old stuff rotting there. I could help.

**Comment by aalex** [comment]
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by revast** [comment]
```
2. Convert existing binary packages

This option might be the easiest if you already have up-to-date packages in place, ideally a ppa for 
trusty or earlier or a debian repository for oldstable. In this case, you can write a small .yml recipe and 
in many cases are done with the package to AppImage conversion. The pkg2appimage script can run .yml recipes.
```

**Comment by revast** [comment]
something like:

```
app: toonloop
binpatch: true

ingredients:
  dist: trusty
  sources: 
    - deb http://archive.ubuntu.com/ubuntu/ trusty main universe
  ppas:
    - ppa:alexandre-quessy/toonloop

```

**Comment by probonopd** [comment]
Actually,

```
app: toonloop
binpatch: true

ingredients:
  dist: precise
  sources: 
    - deb http://archive.ubuntu.com/ubuntu/ precise main universe
  ppas:
    - ppa:alexandre-quessy/toonloop
```

is more like it (it does produce an AppImage), but I fail to get a working JACK setup (as always - JACK is always a red sign for me).

```
me@host:~$ sudo ./out/Toonloop-2.1.18.glibc2.15-x86_64.AppImage 
/bin/bash: /tmp/.mount_ToonloBSixW0/lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
Image ././/share/pixmaps/toonloop_window_icon.png exists.
Window icon is temporarily disabled.
CAPS: video/x-raw-yuv, width=640, height=480, framerate=30/1
Using MIDI bindings file ././/share/toonloop/presets/midi.xml
Cannot connect to server socket err = Connection refused
Cannot connect to server request channel
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Attempt to unlock mutex that was not locked
Aborted
me@host:~$ Unknown error...
terminate called after throwing an instance of 'Jack::JackTemporaryException'
  what():  
```

My JACK server is not configured. I always fail at that. (Why doesn't it configure and start itself? It's no longer 1998, after all...)
